initial fixes for server os

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -24,8 +24,6 @@ export PATH
 conf_arg0=$(basename $0)
 conf_arg0_dir=$(dirname $0)
 conf_root=$PWD
-conf_ips=
-conf_priv="pfexec"
 
 #
 # Build defaults which are unlikely to change, but may be overridden by
@@ -40,7 +38,7 @@ fi
 # We configure the projects framework using a 'configure-projects' file. This
 # is a plain text file which contains the project name, the branch we wish to
 # build it at, and either a URL to a git repository or 'origin' to denote the
-# github.com/joyent/<repo> location. See create_projects.
+# github.com/server-os/<repo> location. See create_projects.
 #
 read -r -d '' configure_projects < default.configure-projects
 
@@ -66,11 +64,14 @@ function check_loc
 	[[ "$(uname -s)" != "SunOS" ]] && fatal "build only works on SunOS"
 	if [[ "$(uname -v)" =~ "joyent_" ]]; then
 		[[ "$(zonename)" == "global" ]] && fatal \
-		    "building in a GZ on SmartOS is not supported"
-	else
-		echo "Not on SmartOS, assuming IPS and sudo"
-		conf_ips=1
-		conf_priv="sudo"
+		    "building in a SmartOS global zone is not supported"
+	else 
+		if [[ "$(uname -v)" =~ "ServerOS" ]]; then
+			[[ "$(zonename)" == "global" ]] && fatal \
+		    	"building in a ServerOS global zone is not supported"
+		else
+			fatal "Requires SmartOS or ServerOS to be built"
+		fi
 	fi
 }
 
@@ -154,7 +155,7 @@ function checkout_project
 function create_projects
 {
 	local dir="projects/local"
-	local git_stem="https://github.com/joyent"
+	local git_stem="git@github.com:server-os"
 
 	[[ -d "$dir" ]] || mkdir -p "$dir" || fatal "failed to create $dir"
 
@@ -166,6 +167,7 @@ function create_projects
 	else
 		echo "Info: no configure-projects file found, using defaults."
 	fi
+
 	echo "$configure_projects" | grep -v '^#' | while read -r line; do
 		local project_dir=$(echo $line | cut -d: -f 1 | sed -e 's/ //g')
 		local project_name=$(basename $project_dir)
@@ -173,27 +175,16 @@ function create_projects
 		local project_branch=$(echo $line | cut -d: -f 2 | sed -e 's/ //g')
 		local project_url=$(echo $line | cut -d: -f 3- | sed -e 's/ //g')
 
-		# special cases for some projects
-		case ${project_name} in
-		'kvm'|'kvm-cmd')
-			git_name="illumos-${project_name}.git"
-			;;
-		'illumos')
-			git_name="illumos-joyent.git"
-			;;
-		'ur-agent')
-			git_name="sdc-ur-agent.git"
-			;;
-		esac
-
 		# process URL keywords
 		case $project_url in
 		'origin'|'')
 			project_url="$git_stem/$git_name"
 			;;
 		esac
+
 		checkout_project "projects/$project_dir" "$project_branch" \
 		    "$project_url"
+		
 	done || fatal "Error encountered when creating projects directory"
 }
 
@@ -206,37 +197,30 @@ function install_pkgin
 	pkglist="$pkglist coreutils gsed pkg_alternatives cdrtools"
 	pkglist="$pkglist py27-sqlite3 nasm pigz smartos-build-tools"
 
-	$conf_priv pkgin -f update || fatal "failed to update pkgsrc repository"
+	pfexec pkgin -f update || fatal "failed to update pkgsrc repository"
 
 	#
 	# Remove legacy packages replaced by the smartos-build-tools package.
 	#
+	# TODO: review if they are present / can be removed from base image
 	for pkg in astmsgtools dmake rpcgen sgstools; do
 		if pkg_info -qe $pkg; then
-			$conf_priv pkg_delete ${pkg}
+			pfexec pkg_delete ${pkg}
 		fi
 	done
 
 	for pkg in $pkglist; do
 		if ! pkg_info -qe $pkg; then
-			$conf_priv pkgin -y install $pkg || fatal \
+			pfexec pkgin -y install $pkg || fatal \
 		    "failed to install $pkg"
 		fi
 	done
 }
 
-function install_ips
-{
-	fatal "Building on ips based systems has yet to be implemented"
-}
-
 function install_packages
 {
-	if [[ -z "$conf_ips" ]]; then
-		install_pkgin
-	else
-		install_ips
-	fi
+	install_pkgin
+
 	[[ $? -eq 0 ]] || fatal "failed to install packages"
 }
 
@@ -319,10 +303,10 @@ function generate_env
 	lprefix=$(echo $conf_root | tr / _)
 	[[ $? -eq 0 ]] || fatal "failed to create lock prefix"
 
-cat > "projects/illumos/illumos.sh" <<EOF
+cat > "projects/illumos-joyent/illumos.sh" <<EOF
 NIGHTLY_OPTIONS="$nopts";			export NIGHTLY_OPTIONS
 GATE="${RELEASE_VER}";				export GATE
-CODEMGR_WS="$conf_root/projects/illumos";	export CODEMGR_WS
+CODEMGR_WS="$conf_root/projects/illumos-joyent";	export CODEMGR_WS
 # NOTE: build_illumos modifies this initial constant
 MAX_JOBS=128
 maxjobs() {
